steps:
  - command: ".buildkite/tests.sh"
    label: "Parallelized test"
    parallelism: 5
    plugins:
      - docker#v3.13.0:
          image: "ubuntu:latest"
          environment:
            - "BUILDKITE_PARALLEL_JOB"
            - "BUILDKITE_PARALLEL_JOB_COUNT"
